scverse/pertpy

pertpy/data/__init__.py
pertpy/data/_datasets.py

As mentioned in https://github.com/theislab/pertpy-tutorials/pull/4, added data loader for subsampled Stephenson2021 dataset. 
The dataset is subsampled to have approx 500 cells per donors (before QC filtering) and batch corrected space is in `adata.obsm['X_scVI']` (mapped to PBMC ref atlas w scArches). Not sure if it's important to have a reference for how the data was preprocessed here, but if needed this should come out on biorxiv in a week or so (submitted today).

Added subsampled Stephenson2021 COVID19 dataset

---

.pre-commit-config.yaml

-   [x] Documentation in `docs` is updated
Changed prettier and isort based on the following issues:
[prettier version problem causing the node incompatibility](https://github.com/scverse/cookiecutter-scverse/pull/144)
[isort incompatibility with newer versions of poetry](https://stackoverflow.com/questions/75269700/pre-commit-fails-to-install-isort-5-11-4-with-error-runtimeerror-the-poetry-co)
-
-

Solve pre-commit prettier and isort version incompatibility issues

---

pertpy/plot/_coda.py
pertpy/plot/_milopy.py
pertpy/tools/_milopy.py
tests/tools/test_milopy.py

1. Change slot name of milo. (From "milo_compositional" to "milo", keep it consistent to "coda")
2. Improve coda.draw_tree(). Make it compatible to MuData and AnnData. Add default settings of using "tree" in .uns and "coda" in MuData.

changes default settings of coda and milo

---

pertpy/plot/_mixscape.py
pertpy/tools/_mixscape.py
tests/tools/test_mixscape.py

1. Change "control" argument in mixscape as required arguments
2. Fix bug in mixscape
3. Improve mixscape documentation

improve mixscape documentation & fix a bug

---

pertpy/tools/_distances/_distances.py

Add the n_jobs support to speed up the pairwise distance computation 
Just add n_jobs support

add n_jobs support for pairwise distance computation

---

pertpy/plot/_coda.py
pyproject.toml

Fixes https://github.com/theislab/pertpy/issues/351 temporarily

Remove statsannotations

---

pertpy/tools/_coda/_base_coda.py

-   [x] Documentation in `docs` is updated
- Added warning notes if acceptance probability of MCMC sampling is too high (>0.95) or too low (<0.6)
Sometimes, the MCMC samplers in scCODA/tascCODA do not converge or converge to the wrong local minimum. This is usually due to bad initialization values and can be fixed by re-running with a different rng key.
An unusually low or high acceptance rate is a good indicator for a misspecified sampler, but there are no strict bounds for good acceptance rates. Therefore, we can only display a message and ask users to check whether results are feasible …

scCODA: add low/high acceptance probability warnings

---

docs/usage/usage.md
pertpy/data/__init__.py
pertpy/data/_datasets.py
pertpy/plot/__init__.py
pertpy/plot/_cinemaot.py
pertpy/tools/__init__.py
pertpy/tools/_cinemaot.py
tests/tools/test_cinemaot.py

Implementation of CINEMA-OT using the ott-jax library. Including an updated usage.md, tl.Cinemaot class and CinemaotPlot class. A test file is included. Let me know if there are any issues.

Implementation of CINEMA-OT for pertpy

---

pertpy/tools/_distances/_distances.py

-   [x] Documentation in `docs` is updated
The documentation examples of `pertpy.tools.Distance` had an outdated naming for the example data, and a minor bug in variable naming.
Both would be fixed in this PR.
n/a
The outdated naming has been adressed in other files in #384 and [this commit](https://github.com/theislab/pertpy-tutorials/commit/5230af1bbc372e9d1e3207dbddcfb94cb46dd681).

fix naming of example data in doc examples

---

pertpy/tools/_distances/_distances.py

Return type of Wasserstein Distance is now float
Fixes issue #385.
The mypy check for another not related distance metric is still failling, as before

wasserstein distance return type float

---

docs/contributing.md
docs/installation.md

Added installations instructions for Apple Silicon (macOs with M-Chips) users. Adapted the installation as well as the contributing guide.
Pertpy uses scvi-tools, which only runs on Apple Silicon machines when installed via a native python version (see [here](https://docs.scvi-tools.org/en/latest/installation.html#apple-silicon)). Hence, also pertpy needs to be installed that way by macOs users with M-chips.

Installation Apple Silicon

---

docs/installation.md
tests/tools/_coda/test_sccoda.py
tests/tools/_coda/test_tasccoda.py
tests/tools/test_cinemaot.py

-   [X] Referenced issue is linked (See #370)
In order to speed up testing, the data used for testing can be subsampled. Here, I examined all tests that use a pertpy dataloader and performed subsampling on the corresponding `AnnData` object.
To ensure that all tests still run, I had to make modifications to two elements that were hardcoded based on the size of the respective data object:
- In `test_tasccoda.test_prepare`: `assert np.sum(mdata["coda"].obsm["covariate_matrix"]) == 8` instead of `== 85`
- In `test_cinemaot.test_pseudobulk`: `expect_num = 9` instead of `expect_num = 20` (because `adata_pb.shape[0]` is 9 when subsampled by 10%)
_Note:_ `TestAugur`, which also relies on pertpy data, has not been modified yet. The tests will be …

Speed up tests by subsampling

---

tests/tools/_metadata/test_cell_line.py

-   [x] Referenced issue: #364 
To remove omplicit modification warnings in cellline tests, `obs` index is converted from integers to strings 

fix Implicit modification warnings in cellline tests

---

docs/installation.md
pertpy/plot/_mixscape.py
pertpy/tools/_cinemaot.py
pertpy/tools/_coda/_base_coda.py
pertpy/tools/_coda/_sccoda.py
pertpy/tools/_coda/_tasccoda.py
pertpy/tools/_distances/_distance_tests.py
pertpy/tools/_scgen/_jax_scgen.py
pertpy/tools/_scgen/_utils.py
pyproject.toml
tests/preprocessing/test_grna_assignment.py
tests/tools/_distances/test_distances.py
tests/tools/_metadata/test_cell_line.py
tests/tools/_perturbation_space/test_simple_perturbation_space.py
tests/tools/test_milo.py
tests/tools/test_mixscape.py

-   [X] Referenced issue is linked (Fixes #355)
All occurrences of numpy Legacy Generator (RandomState) were replaced with the new `numpy.random.Generator`. Whenever an instance of the `numpy.random.Generator` was created, the recommended constructor `default_rng` was used.
I tested that all legacy warnings have disappeared by including the numpy rules from ruff in the pre-commit checks.

Move to new numpy.random.Generator 

---

pertpy/plot/_dialogue.py
pertpy/plot/_scgen.py
pertpy/tools/_perturbation_space/_perturbation_space.py
pertpy/tools/_perturbation_space/_simple.py

-   [X] Documentation in `docs` is updated
Some small bug fixes and docs improvements which I noticed would be useful during the creation of the docs examples. I made the following changes:
- Changed `pt.pl.dl.pairplot` to a static method (and deleted the self parameter). Before, it was necessary to create a `DialoguePlot` object and then call the pairplot method using the created object. Now, the method can be called directly with `pt.pl.dl.pairplot` which matches the convention we have for creating plots so far. The example in the docs was updated as well.
- Fixed error message in `subtract` and `add` methods of `PerturbationSpace` object. Before, the error messages always printed that the reference_key is missing in adata.obs_names, although …

Small bug fixes and docs improvements

---

docs/installation.md
pertpy/tools/_coda/_base_coda.py
pertpy/tools/_coda/_tasccoda.py

-   [X] Referenced issue is linked (Fixes issue #407)
Fix of the `set_fdr` method for tree_agg models (tascCODA models). Since the `summary_prepare` method returns three values for tree_agg models but the previous code in `set_fdr` accepted only two (which is correct in the case of a classical model), an error was thrown. This bug is easily fixed by differentiating between the two models and then either expect the `summary_prepare` method to return two or three values.

Fixed set_fdr for tascCODA models

---

pertpy/tools/_milo.py

It's not immediately clear to me why `def test_count_nhoods_missing_nhoods()` would not capture this

actually use `neighbors_key` in `milo`

---

pertpy/plot/__init__.py
pertpy/plot/_coda.py
pertpy/tools/__init__.py
pertpy/tools/_coda/_base_coda.py
pertpy/tools/_coda/_tasccoda.py

Doesn't fix all issues but enables scCODA on colab. See #357 for scCODA

scope imports of ete3 in tasccoda

---

.github/workflows/test.yml
codecov.yml
pyproject.toml
tests/__init__.py

-   [x] Fixes #428
-   [x] No tests necessary
-   [x] No doc changes necessary
- Changing things so CI fails when coverage collection failed (0%) or upload failed
- Switch to run `coverage` directly instead of using `pytest-cov`
Using `pytest-cov` can sometimes cause problems since it initializes its machinery after pytest has started doing its thing. `coverage run` will work in those circumstances.
Of course that means that pytest can’t prevent adding the current working directory to PYTHONPATH unless the project uses the `src` layout. Experimentally switching the project to src layout worked, but I think that’s out of scope for this PR.

Fix code coverage

---

pertpy/plot/_mixscape.py
pyproject.toml

Removed the dependency (plotnine)
In this pull request, I addressed the issue #425 by removing the dependency on plotnine. Instead, I have implemented the use of matplotlib and seaborn for plotting. Specifically, I updated the `barplot` function and the `perturbscore` function to utilize these libraries, providing a more lightweight solution for the project.
While making these changes, I ensured that the functionality remains consistent, and the transition to matplotlib and seaborn is seamless. The choice of these libraries was made to minimize dependencies and provide a …

Replace plotnine implementation of barplot with seaborn/matplotlib

---

pertpy/tools/_perturbation_space/_discriminator_classifier.py

When preparing (`load`) a dataset stored in a sparse matrix (e.g. Norman dataset) for processing with `DiscriminatorClassifierSpace`, an error is thrown:
This is due to our custom implementation of the dataset storing the data for training the NN: `PLDataset`. When calling `len` for a `PLDataset` object, we call `len(matrix)`, which throws the error above in case the matrix is sparse. By simply changing it to `matrix.shape[0]`, this problem is solved. The previous behavior is unaltered, since `a.shape[0] == len(a)`.

DiscriminatorClassifier compatibility with sparse matrices

---

pertpy/tools/_perturbation_space/_simple.py

-   [X] Documentation in `docs` is updated
`CentroidSpace` calculates the centroid for all cells of a given perturbation. The resulting AnnData object will have one row for each perturbation. The objective of this pull request is to enhance the annotation of the returned AnnData object, thereby simplifying its downstream usage. Specifically, the following modifications in the `CentroidSpace.compute` method have been made:
- I included the .obs column specified in the parameter`target_col` (the column containing perturbation annotations) as a .obs column in the output. Although perturbation information is also stored as an index in the returned adata, having it in .obs is useful, for instance, for the creation of a colored UMAP plot (see …

CentroidSpace AnnData Annotations

---

pertpy/tools/_dialogue.py

-   [X] Referenced issue is linked (closes #463)
-   [X] Documentation in `docs` is updated (I deleted the docs example, since the protected method will not appear in the docs)
I changed Dialogue's `load` method from public to protected to prevent confusion with the typical functionality of `load` methods in pertpy.

Make dialogue's load protected

---

pertpy/tools/_milo.py

-   [X] Referenced issue is linked (closes #457)
As described in the referenced issue, the subsetting in `milo.plot_da_beeswarm` currently triggers an error. Essentially, our goal is to have the ability to choose specific subgroups in `.obs` to plot. I fixed the issue almost exactly as suggested in the issue, correcting how the respective rows are selected from the AnnData.
**Example**
```
pt.pl.milo.da_beeswarm(mdata)
```
With the fix we now have:
```
milo.plot_da_beeswarm(mdata, subset_nhoods=['Oligo', 'Microglia'])
```

Fix subsetting of milo.plot_da_beeswarm

---

docs/usage/usage.md
pertpy/data/__init__.py
pertpy/data/_dataloader.py
pertpy/data/_datasets.py

Add combosciplex

---

pertpy/tools/_distances/_distances.py
pertpy/tools/_perturbation_space/_perturbation_space.py
pertpy/tools/_perturbation_space/_simple.py
tests/tools/_distances/test_distances.py
tests/tools/_perturbation_space/test_simple_perturbation_space.py

Adds KNN imputation using pynndescent. Useful for label transfer in perturbation spaces.
Also renames "perturbations" to "perturbation" as default target column for some spaces.

Add knn imputation

---

pertpy/tools/_perturbation_space/_simple.py

-   [X] Referenced issue is linked (closes #501)
-   [X] Documentation in `docs` is updated
- Added a parameter explanation for the `groups_col` parameter. There are use cases where one might want to specify groups to consider in addition to the perturbation. That way, one can, for example, summarize perturbations for each cell type individually, so that the resulting pseudobulk object would have separate datapoints for pert1_celltype1, pert1_celltype2, and so on. However, the default setting for this parameter should be `None`, and the parameter should be explained in the docs.
- Deleted `groups_col` parameter from the docs example (previously, `groups_col` was set to the same value as `target_col`, which is useless since decoupler then …

Pseudobulk improvements

---

pertpy/metadata/_cell_line.py

- Metadata classes should load data more lazily #478: `__init__` loads only the ones that are requested on annotate. The remainig files are downloaded upon request of annotating. However, all the files are forced to be downloaded when initializing the lookup object. Thus it takes much more time to initialize the look up object if all the files haven't downloaded before. Do you probably have any other suggestions?
- Improve annotate docstring in cell line #479: Add Cancerxgene in the docstring. Also, rename all the downloaded files and  their corresponding variables to be more readable. …

Update cell line meta data class

---

pertpy/metadata/_cell_line.py
pertpy/metadata/_drug.py
pertpy/metadata/_look_up.py
pertpy/metadata/_moa.py
tests/metadata/test_cell_line.py

#535: update cell line metadata to 23Q4
#478: Download the metadata upon specific request

Lazily metadata loading

---

pertpy/plot/_coda.py
pertpy/tools/_coda/_base_coda.py

Rename cmap to palette

---

pertpy/tools/_perturbation_space/_discriminator_classifiers.py
tests/tools/_perturbation_space/test_discriminator_classifiers.py

-   [X] Referenced issue is linked (closes #562)
-   [X] If you've fixed a bug or added code that should be tested, add tests!
-   [X] Documentation in `docs` is updated
- Replaced three separate methods (`load`, `train`, and `get_embeddings`) in the `MLPClassifierSpace` with a single `compute` method. The motivation for this is to unify the API, aligning it with other perturbation space methods, which all feature a `compute` method.
- The `load`, `train`, and `get_embeddings` methods persist, however, they now trigger a `DeprecationWarning` when called that points users to the new `compute` method.

Compute method for MLPClassifierSpace

---

pertpy/tools/_augur.py

When running Augur predict, I stumbled upon this warning: 
This should silence the warning.

Silence pandas groupby() warning when running Augur predict

---

pertpy/data/__init__.py
pertpy/data/_datasets.py

Added a dataloader for the sciPlexGxE HPRT1 & MMR GxE screens from https://www.cell.com/cell-genomics/fulltext/S2666-979X(23)00339-7. 
The second screen is too heavy to be added yet (ca. 35GB), so I will upload the concatenation scripts in the pertpy-datasets repo.

Add sciplex-GxE dataloader

---

pertpy/metadata/_cell_line.py
pertpy/tools/_differential_gene_expression/_statsmodels.py

- Fixed the logger error message in the cell line metadata annotation. The code will still fail, but now the informative logging message will be shown.
- The parameter specifying the GDSC dataset can now also be provided as a string. Feel free to reject this change, as I might be the only user making the mistake of providing it as a string instead of an integer. The latter causes the method to always use GDSC dataset 2 without specifically stating it, which might be overlooked by the user. I also added a test that the parameter is set to `1` or `2` and otherwise throw an error.
- The most important change is in the `annotate_from_gdsc` method, which now uses the correct GDSC data to compute. Previously, the code would fail for me if GDSC2 was used.
- Adapted the …

Metadata GDSC annotation improvements

---

pertpy/tools/_mixscape.py

-   [X] Referenced issue is linked (#617)
- Added `use_raw=False` to the `sc.tl.rank_genes_groups` method call
- Currently, `Mixscape.mixscape` fails for `adata` objects where `adata.raw` is present. This is due to the internal call of `sc.tl.rank_genes_groups`, which uses `adata.raw` by default for computation if `use_raw` is not explicitly set to `False`. If a layer is specified when calling `Mixscape.mixscape`, this will cause the `rank_genes_groups` method to fail with the error: `ValueError: Cannot specify "layer" and have "use_raw=True"`. If no layer is specified, `rank_genes_groups` will use `adata.raw` for computation, potentially leading to errors like the one reported in #617.
**Discussion point**
- Currently, the layer is set to …

Fix layer handling in Mixscape.mixscape to resolve errors with adata.raw

---

pertpy/preprocessing/_guide_rna.py
pertpy/tools/_milo.py
pertpy/tools/_perturbation_space/_discriminator_classifiers.py

The new scipy version (1.14+) deprecate the use of `.A` to access the array value of sparse matrices, which breaks some functions within pertpy. This PR fixes the issue by using the `toarray()` function to access the array value of sparse matrices.
The PR fix works on both the new scipy version (1.14+) and older scipy version (1.13.1) as well. However, I was only able to test the guide RNA and milo functions, not the discriminator classifier function.

Support for scipy 1.14

---

.github/workflows/test.yml
docs/installation.md
docs/usage/usage.md
pertpy/tools/__init__.py
pertpy/tools/_cinemaot.py

**Issue**
The `lazy_import` introduced in PR #647 solves the issue of a failed pertpy import when not all optional dependencies are installed. However, since the classes were wrapped in multiple functions, they were no longer correctly displayed in the docs.
- Updated the implementation of the `lazy_import` method: Instead of wrapping the class in a function, I created a `Placeholder` class that raises an `ImportError` when called. This should be equivalent to the previous implementation functionality-wise. I verified that one can import pertpy when optional dependencies are not installed in the environment, and that the docs builds correctly as long as the optional dependencies are installed.
- Removed python version descriptions from the Apple Silicon …

Fix docs rendering for classes using lazy import

---

.github/workflows/test.yml
pyproject.toml

-   [X] Referenced issue is linked (closes #652)
The bug in PyDESeq2 caused by the new Anndata release has been fixed (see https://github.com/owkin/PyDESeq2/issues/306), so we can remove the Anndata pin.

Remove anndata pin

---

pertpy/tools/_mixscape.py

While testing the `pt.tl.Mixscape.plot_barplot` method, I noticed that the legend is positioned weirdly - sometimes overlapping with another plot or completely outside the plotting area - since the legend position was hard-coded. I changed that; the `bbox_to_anchor` for the legend position can still be set as a parameter, but is `None` by default.
I also added missing docstring explanations for other parameters of that method.

Fix legend position for pt.tl.Mixscape.plot_barplot

---

pyproject.toml

I don't remember why we added it.

Remove explicit anndata in dependencies

---

.pre-commit-config.yaml
pertpy/tools/_perturbation_space/_perturbation_space.py
tests/tools/_perturbation_space/test_simple_perturbation_space.py

-   [x] Referenced issue is linked (NA; addresses reviewer comment)
-   [x] Documentation in `docs` is updated (NA)
Certainty is quantified as the fraction of nearest neighbors belonging to the classified (i.e. the most abundant) label compared to the total number of nearest neighbors. This is saved in a new specified column in adata.obs as a score between 0 and 1. Cells that had a label to begin with will get highest certainty assigned.

Add uncertainty score in KNN label_transfer in PerturbationSpace

---

pertpy/tools/_coda/_base_coda.py
pertpy/tools/_mixscape.py

-   [X] Referenced issue is linked (#659, #598, https://github.com/theislab/single-cell-best-practices/issues/271 - I'll close the issues manually once this PR is merged, because I'd like to add one comment each to explain the changes to the users who opened the issue)
**mixscape.plot_barplot issue**
As reported in #659, the effects bar plot wasn't visible. Adding a simple `plt.tight_layout()` fixed the issue. I also resolved some warnings that occurred during plotting by using `ax.set_xticks` instead of `ax.set_xticklabels`.
**sccoda.plot_effects_barplot**
Reported in #598 and https://github.com/theislab/single-cell-best-practices/issues/271.
These issues were basically reporting the same problem: there was a bug in the code that caused …

Fixed plotting for mixscape.plot_barplot and sccoda.plot_effects_barplot

---

pertpy/tools/_differential_gene_expression/_edger.py
tests/tools/_differential_gene_expression/test_edger.py

Fixes to pass broken rpy2 tests. 
This drops column names from the design matrix in R object. I'm not 100% sure it behaves well in all cases with complex designs, but I've added a test to ensure I get the same ranking of genes with PyDESeq2.

Fix edgeR rpy2 tests

---

pertpy/_doc.py
pertpy/metadata/_cell_line.py
pertpy/preprocessing/_guide_rna.py
pertpy/tools/_augur.py
pertpy/tools/_cinemaot.py
pertpy/tools/_coda/_base_coda.py
pertpy/tools/_dialogue.py
pertpy/tools/_differential_gene_expression/_base.py
pertpy/tools/_enrichment.py
pertpy/tools/_milo.py
pertpy/tools/_mixscape.py
pertpy/tools/_perturbation_space/_simple.py
pertpy/tools/_scgen/_scgen.py
pyproject.toml

As discussed and mentioned in #702, the `show` parameter in all our plotting functions is somewhat obsolete. Additionally, if `show=True` and `return_fig=True`, an empty figure is returned because the Matplotlib plot is cleared by `show()`.  Hence, I removed the `show` parameter from all plotting functions and `plt.show()` is called by default, unless `return_fig=True`.
Additionally, for `pt.tl.Sccoda.plot_effects_barplot` and `pt.tl.Sccoda.plot_boxplots`, when `plot_facets=True`, an empty plot was returned since the plot wasn't created directly via Matplotlib. This issue has now been fixed too.

Fix empty figure returns when show=True in plotting functions

---

pertpy/preprocessing/_guide_rna.py
pertpy/tools/_dialogue.py

Originally contributed by @grpinto.
Fixes #668 where users requested greater flexibility in specifying the feature space for the Dialogue implementation. Previously, the Dialogue function was limited to using PCA via the `_pseudobulk_pca` method, which prevented users from easily experimenting with or formally documenting the use of alternative feature reduction techniques.
Changes Introduced:
Refactored Feature Extraction:
The internal function call has been updated from `_pseudobulk_pca` to `_pseudobulk_feature_space`. Small adjustment to make the label flexible to the user.
Existing functionality has been preserved. For users who rely on the default PCA behavior, the changes maintain backward compatibility while offering an easy path to extend or replace the feature space as needed. …

Allow Custom Feature Spaces in Dialogue

---

pertpy/tools/_mixscape.py
tests/tools/test_mixscape.py

I made the following updates to `pt.tl.Mixscape()`:  
- Added a `de_layer` parameter to `mixscape()`, since DEG computation should be based on `adata.X`, while the rest of the method operates on `adata.layers[X_pert]`, i.e., the perturbation signature. Seurat’s implementation also includes this parameter (see [here](https://github.com/satijalab/seurat/blob/9755c164d99828dbc5dd9c8364389766cd4ff7fd/R/mixscape.R#L692)).  
- Added a `test_method` parameter to `mixscape()` and `lda()` to specify the test used for DEG computation. Seurat uses Wilcoxon by default (see [here](https://github.com/satijalab/seurat/blob/9755c164d99828dbc5dd9c8364389766cd4ff7fd/R/mixscape.R#L1316)), while pertpy previously always used a t-test. Hence, users can now choose …

Align Mixscape with Seurat’s implementation

---

pertpy/metadata/_cell_line.py
tests/metadata/test_cell_line.py

- Added a method to annotate drug responses using the DepMap PRISM Repurposing 19Q4 secondary screen dose-response curve parameters.
- If multiple measurements for one cell line and drug are present, we take the mean IC50, EC50, and AUC values.
- PRISM IC50, EC50, and AUC values are stored in `adata.obs`.
- Added AUC annotation for GDSC data (stored in the same GDSC file we already downloaded for ln(IC50) annotation).

PRISM drug response metadata annotation

---

pertpy/tools/_distances/_distances.py

Changing default cell-wise distance metric for the E-distance from squared euclidean to just euclidean. Makes more sense as a default.

Change cell_wise_metric from "sqeuclidean" to "euclidean" for edist

---

pertpy/tools/_mixscape.py

-   [ ] Referenced issue is linked N/A
-   [ ] If you've fixed a bug or added code that should be tested, add tests! N/A
-   [ ] Documentation in `docs` is updated N/A
Speedup Mixscape's lda function by removing unused computations of sc.tl.ingest.
The whole `scanpy.tools.ingest` computations, including neighborhood search, has been used in the `Mixscape.lda` computation until now.
However, its only the projection into reference PCA space that is needed. Which is [this part](https://github.com/scverse/scanpy/blob/cb83cfc08536eaca43e593218da14fae37c7e6dc/src/scanpy/tools/_ingest.py#L360) of scanpy's ingest.
This PR changes the `scanpy.tools.ingest` call with the required computations only, mean-centering the query matrix, …

Speedup Mixscape's lda function

---

pyproject.toml

While trying to run a `tascCODA` model I ran into an error caused by a check done here:
https://github.com/scverse/pertpy/blob/512c0e0f3eb25f2df915e5a4fcbeb7dcbddbd6e4/pertpy/tools/_coda/_tasccoda.py#L207
The error raised was:
```python
AttributeError: module 'toytree' has no attribute 'core'
```
`toytree.core` was introduced in version `3.0.0`: https://github.com/eaton-lab/toytree/blob/3.0.0/toytree/__init__.py
I was running `toytree-2.0.5`, upgrading to `toytree-3.0.10` fixed the bug.
This just ads a pin in `pyproject.toml` to make the requirement explicit.
(Congrats on version 1 release!)

(fix) Add `toytree>=3.0` pin to `pyproject.toml`

---

.github/workflows/test_tutorials.yml
pertpy/tools/_coda/_base_coda.py

Run notebooks in CI

---

pertpy/tools/_coda/_base_coda.py
pertpy/tools/_distances/_distance_tests.py
pertpy/tools/_distances/_distances.py
tests/tools/_distances/test_distances.py

Fixes https://github.com/scverse/pertpy/issues/823
1. Now allows for:
```python
import pertpy as pt
adata = pt.dt.distance_example()
dist = pt.tl.Distance(metric="mmd")
df = dist.pairwise(adata, groupby="perturbation", gamma=0.5)
```
2. Improves typing for Metrics

Add support for gamma parameter in MMD distance

---

pertpy/tools/_coda/_tasccoda.py
pyproject.toml
tests/tools/_coda/test_tasccoda.py

This PR fixes a bug in `pertpy.tl.Tasccoda.load` where providing an invalid string to the `type` parameter would not raise an error, leading to silent and incorrect behavior.
Now, the function validates the `type` parameter and raises a clear `ValueError` if it's not one of the supported options ("cell_level" or "sample_level"), guiding the user towards the correct usage.
- Added an `elif` condition to explicitly check for `"sample_level"`.
- The final `else` block now raises a `ValueError` with an informative message.
- Updated `pyproject.toml` to include `tcoda` dependencies in the test environment, which was necessary to run the relevant test suite.
All tests for tascCoda passed correctly.
Closes #838 
This is my …

Fix: Validate 'type' parameter in Tasccoda.load

---

.github/workflows/test.yml
.github/workflows/test_tutorials.yml
.gitignore
.readthedocs.yml
pertpy/tools/__init__.py
pertpy/tools/_perturbation_space/_comparison.py
pertpy/tools/_perturbation_space/_discriminator_classifiers.py
pertpy/tools/_perturbation_space/_perturbation_space.py
pertpy/tools/_perturbation_space/_simple.py
pyproject.toml
tests/tools/_distances/test_distances.py

- Replaces the existing scvi-tools implementation of the MLPClassifier with a pure Jax/Flax implementation
- Removes the mandatory scvi-tools dependency and gates Scgen behind an import lookup

Remove scvi-tools dependency
