.flake8
.github/pull_request_template.md
.github/workflows/build_package.yml
noxfile.py
pertpy/__init__.py
pertpy/__main__.py
pertpy/cli/custom_cli/click.py
pertpy/cli/custom_cli/levenstein_distance.py
pertpy/cli/custom_cli/questionary.py
pertpy/cli/custom_cli/rich.py
poetry.lock
pyproject.toml
tests/test_main.py

Signed-off-by: zethson <lukas.heumos@posteo.net>

add pypi-latest & architecture

---

pertpy/data/__init__.py
pertpy/data/_datasets.py
pertpy/plot/__init__.py
pertpy/tools/__init__.py
pertpy/tools/augurpy/evaluate.py

Some refactoring. __inits__, datasets, current version for tutorial, removed some error messages.

add inits for plots, fix  error messages and output, tutorial version

---

pertpy/data/__init__.py
pertpy/data/_datasets.py

add kang dataset

---

pertpy/tools/_augurpy.py
tests/tools/test_augur.py

Fix numpy array support for augurpy

---

pertpy/tools/_mixscape.py
tests/tools/test_mixscape.py

fix mixscape default setting of layer

---

.github/workflows/publish_docs.yml
docs/requirements.txt
pertpy/tools/__init__.py
poetry.lock
pyproject.toml

Readding ete3 as an optional dependency

Readding ete3

---

pertpy/tools/__init__.py

fix #207 ete3 warning masks other ImportErrors

---

pertpy/tools/_coda/_sccoda.py
pertpy/tools/_coda/_tasccoda.py

-   [x] Documentation in `docs` is updated
Added clarification for sample identifiers to the docstrings of the load methods for scCODA and tascCODA
no technical changes
In response to #224

docstring enhancement for sample identifiers

---

pertpy/tools/_metadata/_cell_line.py

White space in Sanger Bulk rna expression data is removed.
#336 

Remove whitespace in bulk RNA expression

---

docs/conf.py
pertpy/plot/_milopy.py

Fixes https://github.com/theislab/pertpy/issues/238

palette support for da_neighborhoods

---

pertpy/plot/_coda.py
pertpy/tools/_coda/_base_coda.py
pyproject.toml

Fixes https://github.com/theislab/pertpy/issues/358

Set run nuts random key to 0 by default.

---

pertpy/data/_datasets.py

Fixes https://github.com/theislab/pertpy/issues/373

Fix stephenson 2021 and refactor

---

pertpy/plot/_milopy.py
pertpy/tools/_distances/_distances.py

-   [X] Referenced issue is linked (see #408)
- Added an example for `pt.pl.milo.nhood_graph` as discussed in #408. When using colab, an upgrade to `matplotlib` 3.8 is required
- Deleted a duplicated bullet point in the `pertpy.tools.Distance` API

Added example for pt.pl.milo.nhood_graph

---

pyproject.toml

Removes a few dependencies that are transitive anyways

Removing dependencies

---

pertpy/tools/_coda/_base_coda.py

Optimize from_scanpy

---

docs/installation.md
docs/usage/usage.md
pertpy/tools/_coda/_base_coda.py
pertpy/tools/_coda/_tasccoda.py
pyproject.toml

Add more detailed tool explanations

---

pertpy/tools/_augur.py

-   [ #173 ] Referenced issue is linked
Changed predict function in _Augur.py so that it does not make changes to the input data. And improve speed of prediction. 

fixed augur runtime

---

pertpy/tools/_coda/_base_coda.py
pertpy/tools/_coda/_sccoda.py
pertpy/tools/_coda/_tasccoda.py

Fix jax config

---

pertpy/plot/_milopy.py
pertpy/tools/_milo.py

Fixes (or patches?) https://github.com/theislab/pertpy/issues/525 plus small changes to error messages

Small fixes to milo.plot_da_beeswarm

---

pertpy/tools/_cinemaot.py
pertpy/tools/_coda/_base_coda.py
pertpy/tools/_differential_gene_expression/_edger.py
pertpy/tools/_distances/_distances.py
pyproject.toml
tests/tools/_distances/test_distances.py

Fix jax random array

---

pertpy/tools/_differential_gene_expression/_pydeseq2.py
tests/tools/_differential_gene_expression/test_pydeseq2.py

Closes https://github.com/scverse/pertpy/issues/690
Removed updates to design matrix, no longer needed with PyDESeq2 using formulaic + test 

Removing design matrix workaround

---

.github/pull_request_template.md
.github/workflows/build.yml
.pre-commit-config.yaml
CODE_OF_CONDUCT.md
docs/contributing.md
docs/index.md
docs/usage/usage.md
pertpy/metadata/_cell_line.py
pertpy/tools/_coda/_base_coda.py
pertpy/tools/_mixscape.py
pyproject.toml
tests/tools/test_mixscape.py

Fixes https://github.com/scverse/pertpy/issues/694
- Original we were casting and rounding the probabilities from float to int which was not intended. This PR restores the earlier correct behavior
- Updates Ruff and mypy to the latest versions
- Removes a few more warnings

Fix probability data type

---

pyproject.toml

Fixes https://github.com/scverse/pertpy/issues/700

Lower bound for scikit-learn

---

pyproject.toml

Remove leidenalg from requirements

---

.github/workflows/test.yml
pertpy/tools/_mixscape.py
pyproject.toml

Starting to use fast-array-utils for a bit better sparse support in mixscape

Optimize mixscape

---

docs/_templates/autosummary/class.rst
docs/conf.py
docs/index.md

- enables myst-nb
- Fixes mixscape dropdown

mixscape dropdown

---

pertpy/tools/_mixscape.py

-   [ ] Referenced issue is linked N/A
-   [ ] If you've fixed a bug or added code that should be tested, add tests! N/A
-   [ ] Documentation in `docs` is updated N/A
Its most likely not doing anything, I expect the import to be cached the least or if repeatedly done even omitted by the interpreter? In any case, prettier I think.

Move pynndescent import out of for-loop

---

.github/release-drafter.yml
.github/workflows/test.yml
.pre-commit-config.yaml
docs/changelog.md
pertpy/__init__.py
pertpy/data/_dataloader.py
pertpy/metadata/_cell_line.py
pertpy/metadata/_compound.py
pertpy/metadata/_look_up.py
pertpy/metadata/_metadata.py
pertpy/metadata/_moa.py
pertpy/tools/_augur.py
pertpy/tools/_mixscape.py
pyproject.toml
tests/conftest.py
tests/metadata/test_cell_line.py
tests/tools/_coda/test_sccoda.py
tests/tools/_distances/test_distance_tests.py
tests/tools/test_augur.py
tests/tools/test_dialogue.py

- Simplify Metadata errors
- Remove slow mark

Simplify Metadata errors

---

pertpy/tools/_coda/_base_coda.py

This commit ensures that every scCODA plot function with a `palette` parameter accepts at least a string value (color map name) and a `matplotlib.colors.ListedColormap` object (color map). The default behaviour remains unchanged and the new function interfaces are backwards-compatible.
These changed code is untested.
I would appreciate some guidance regarding how to add tests covering the new code and update the documentaion.
In the meantime, I leave this as a draft.
This fixes https://github.com/scverse/pertpy/issues/771.

Standardize scCODA plot palette interface

---

pertpy/tools/_coda/_base_coda.py

Fixes https://github.com/scverse/pertpy/issues/778

fix docstring of example for effects_umap

---

.github/ISSUE_TEMPLATE/bug_report.yml

Just a few things I noticed when opening bug reports.
The current issue template for bug reports
1. includes `pertpy` as a loaded model when using a notebook cell, but not when running from a python session, and
2. instructs to paste the session info as Markdown but renders it as a python code block.

Issue template fix

---

pertpy/tools/_coda/_base_coda.py
pertpy/tools/_distances/_distances.py
pertpy/tools/_milo.py
pertpy/tools/_mixscape.py
pertpy/tools/_perturbation_space/_discriminator_classifiers.py
tests/tools/_differential_gene_expression/test_edger.py
tests/tools/_differential_gene_expression/test_pydeseq2.py
tests/tools/test_milo.py
tests/tools/test_scgen.py

Fixes https://github.com/scverse/pertpy/issues/785
Fixes https://github.com/scverse/pertpy/issues/772
- improves mixscape performance for sparse
- improves milo and mixscape plotting to prepare for seaborn 0.14.0
- pydeseq2 and edger related tests are now skipped if they are not installed

fix seaborn 0.14 compat & testing dependencies

---

README.md
docs/installation.md

Add conda-forge to installation instructions

---

pertpy/tools/_milo.py

This PR closes #786 regarding the removal of the global `activate()` function of `rpy2`. All conversions are now executed through `localconverter`.

Fix compatibility with rpy 3.6.0 in milo

---

README.md
docs/installation.md
pertpy/__init__.py
pertpy/tools/_milo.py
pertpy/tools/_perturbation_space/_perturbation_space.py
pyproject.toml
tests/tools/test_milo.py
tests/tools/test_scgen.py

Fixes https://github.com/scverse/pertpy/issues/175
- Adds a "pydese2" solver for milo
| edgeR | pyDESeq2 |
|-------|----------|
| ![Image](https://github.com/user-attachments/assets/2c04933f-93ce-4b91-83b4-4e1bd6dee515) | ![Image](https://github.com/user-attachments/assets/cad3c7b0-132a-4ae9-8496-25f81c732b47) |
| ![Image](https://github.com/user-attachments/assets/a19af6d1-e5e9-4c2e-ae35-2ca3aacfba51) | ![Image](https://github.com/user-attachments/assets/5894edaa-796a-427d-9e1b-4b2e094383ff) |

Add milo pydeseq2 solver

---

docs/index.md

- Simplifies guide assignment tutorial
- Fixes headers not expanding in the tutorials

Simplify guide assignment tutorial

---

pertpy/tools/_milo.py

Fixes https://github.com/scverse/pertpy/issues/819

Fix milo output writing

---

pertpy/metadata/_cell_line.py
pertpy/metadata/_drug.py
pertpy/metadata/_moa.py
pertpy/tools/_differential_gene_expression/_simple_tests.py

Fixes https://github.com/scverse/pertpy/issues/859

metadata to scverse AWS
